name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14
        cache: "yarn"
    - name: Install yarn
      run: yarn install --pure-lockfile --prefer-offline
    - name: run prettier
      run: yarn run prettier --check sigcc
  stylelint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14
        cache: "yarn"
    - name: Install yarn
      run: yarn install --pure-lockfile --prefer-offline
    - name: Run stylelint
      run: yarn csslint
  eslint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14
        cache: "yarn"
    - name: Install yarn
      run: yarn install --pure-lockfile --prefer-offline
    - name: Run eslint
      run: yarn jslint
  black:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install black
      run: python3 -m pip install -r dev-requirements.txt
    - name: Run black
      run: black --check .
